services:
  resultados_nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: resultados_nginx
    ports:
      - 82:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - resultados_db
      - resultados_app
    networks:
      - kuali_network
  resultados_db:
    image: mysql:latest
    container_name: resultados_db
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: resultados
      MYSQL_USER: resultados
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - kuali_network
  resultados_app:
    container_name: resultados_app
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - kuali_network
    ports:
      - "9002:9000"
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - kuali_network
  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
    networks:
      - kuali_network
  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - resultados_db
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - kuali_network
  pint: 
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "/var/www/html/vendor/bin/pint"]
    networks:
      - kuali_network

networks:
  kuali_network:
    external: true